version: 2.1

orbs:
  cypress: cypress-io/cypress@1.11.0

workflows:
  main:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install

jobs:
  install:
    docker:
      - image: cypress/base
    steps:
      - checkout
      - run: npm ci
      - persist_to_workspace:
          root: /root
          paths:
            - project
            - .cache/Cypress
  lint:
    docker:
      - image: cypress/base
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run lint
  test:
    docker:
      - image: cypress/base
    steps:
      - attach_workspace:
          at: ~/
      - run: npm start
